#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""
gen_devices_table.py — parse kmod/devices/*.conf and emit devices_table.generated.c.

Usage:
  gen_devices_table.py --devices-dir kmod/devices --output tools/kmod_loader/devices_table.generated.c
"""

import argparse
import configparser
import glob
import os
import re
import sys


def parse_conf(path):
    cp = configparser.ConfigParser()
    cp.read(path)
    required = ["identity", "match", "modversions", "struct_module", "vermagic"]
    for sec in required:
        if sec not in cp:
            die(f"{path}: missing [{sec}] section")

    ident = cp["identity"]
    for key in ("name", "arch"):
        if key not in ident:
            die(f"{path}: [identity] missing '{key}'")
    name = ident["name"]
    if not re.match(r"^[a-z0-9_]+$", name):
        die(f"{path}: invalid name '{name}' (must match ^[a-z0-9_]+$)")

    match = cp["match"]
    if "kernelrelease" not in match:
        die(f"{path}: [match] missing 'kernelrelease'")

    mv = cp["modversions"]
    for key in ("module_layout", "_printk", "memcpy", "memset"):
        if key not in mv:
            die(f"{path}: [modversions] missing '{key}'")

    sm = cp["struct_module"]
    for key in ("this_module_size", "module_init_offset", "module_exit_offset"):
        if key not in sm:
            die(f"{path}: [struct_module] missing '{key}'")

    vm = cp["vermagic"]
    if "string" not in vm:
        die(f"{path}: [vermagic] missing 'string'")

    provenance = cp["provenance"] if "provenance" in cp else {}

    return {
        "name": name,
        "description": ident.get("description", ""),
        "arch": ident["arch"],
        "kernelrelease": match["kernelrelease"],
        "modversions": {k: parse_hex(v, f"{path}:[modversions].{k}") for k, v in mv.items()},
        "struct_module": {k: parse_hex(v, f"{path}:[struct_module].{k}") for k, v in sm.items()},
        "vermagic": vm["string"].strip('"'),
        "verified": provenance.getboolean("verified", fallback=True) if provenance else True,
    }


def parse_hex(value, where):
    value = value.strip()
    if not re.match(r"^0x[0-9a-fA-F]+$", value):
        die(f"{where}: not a valid hex literal: {value}")
    return int(value, 16)


def die(msg):
    print(f"gen_devices_table: error: {msg}", file=sys.stderr)
    sys.exit(1)


def c_string(s):
    """Escape a Python string for a C string literal."""
    out = []
    for ch in s:
        if ch == "\\" or ch == "\"":
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif 0x20 <= ord(ch) < 0x7f:
            out.append(ch)
        else:
            out.append(f"\\x{ord(ch):02x}")
    return "\"" + "".join(out) + "\""


def emit(entries, output_path):
    lines = []
    lines.append("/* SPDX-License-Identifier: GPL-2.0-or-later */")
    lines.append("/* Generated by tools/gen_devices_table.py. DO NOT EDIT.")
    lines.append(" * Source: kmod/devices/ *.conf */")
    lines.append("")
    lines.append("#include \"devices_table.h\"")
    lines.append("")
    lines.append("__attribute__((used))")
    lines.append("const struct device_entry g_devices[] = {")
    for e in entries:
        lines.append("    {")
        lines.append(f"        .name                = {c_string(e['name'])},")
        lines.append(f"        .description         = {c_string(e['description'])},")
        lines.append(f"        .arch                = {c_string(e['arch'])},")
        lines.append(f"        .match_kernelrelease = {c_string(e['kernelrelease'])},")
        lines.append(f"        .module_layout_crc   = 0x{e['modversions']['module_layout']:08x}u,")
        lines.append(f"        .printk_crc          = 0x{e['modversions']['_printk']:08x}u,")
        lines.append(f"        .memcpy_crc          = 0x{e['modversions']['memcpy']:08x}u,")
        lines.append(f"        .memset_crc          = 0x{e['modversions']['memset']:08x}u,")
        lines.append(f"        .this_module_size    = 0x{e['struct_module']['this_module_size']:08x}u,")
        lines.append(f"        .module_init_offset  = 0x{e['struct_module']['module_init_offset']:08x}u,")
        lines.append(f"        .module_exit_offset  = 0x{e['struct_module']['module_exit_offset']:08x}u,")
        lines.append(f"        .vermagic            = {c_string(e['vermagic'])},")
        lines.append(f"        .verified            = {1 if e['verified'] else 0},")
        lines.append("    },")
    lines.append("    { .name = 0 } /* sentinel */")
    lines.append("};")
    lines.append("")
    lines.append("__attribute__((used))")
    lines.append(f"const size_t g_devices_count = {len(entries)};")
    lines.append("")
    with open(output_path, "w") as f:
        f.write("\n".join(lines))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--devices-dir", required=True)
    p.add_argument("--output", required=True)
    args = p.parse_args()

    conf_files = sorted(glob.glob(os.path.join(args.devices_dir, "*.conf")))
    if not conf_files:
        die(f"no .conf files found in {args.devices_dir}")

    entries = [parse_conf(f) for f in conf_files]
    names = [e["name"] for e in entries]
    if len(set(names)) != len(names):
        die("duplicate device names detected across .conf files")

    emit(entries, args.output)
    print(f"gen_devices_table: emitted {len(entries)} entries → {args.output}")


if __name__ == "__main__":
    main()
