/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Generated by tools/kh_crc. DO NOT EDIT.
 * Source: kmod/exports.manifest
 * Contract 4 (algorithm freeze): CRC values here are stable forever. */
#ifndef _KERNELHOOK_KH_SYMVERS_H_
#define _KERNELHOOK_KH_SYMVERS_H_

/* Relies on _MODVER_ENTRY from kmod/shim/shim.h being in scope. */

#define KH_DECLARE_VERSIONS() \
    _MODVER_ENTRY(__modver_kh_hook_prepare, 0xe1e2e1f4u, "hook_prepare"); \
    _MODVER_ENTRY(__modver_kh_hook_install, 0x1f641515u, "hook_install"); \
    _MODVER_ENTRY(__modver_kh_hook_uninstall, 0x11902138u, "hook_uninstall"); \
    _MODVER_ENTRY(__modver_kh_hook, 0xd3e76aacu, "hook"); \
    _MODVER_ENTRY(__modver_kh_unhook, 0x335ffb6au, "unhook"); \
    _MODVER_ENTRY(__modver_kh_hook_chain_add, 0x2aa1691bu, "hook_chain_add"); \
    _MODVER_ENTRY(__modver_kh_hook_chain_remove, 0x6243efd4u, "hook_chain_remove"); \
    _MODVER_ENTRY(__modver_kh_hook_wrap, 0x193a95acu, "hook_wrap"); \
    _MODVER_ENTRY(__modver_kh_hook_unwrap_remove, 0xb885b3a5u, "hook_unwrap_remove"); \
    _MODVER_ENTRY(__modver_kh_hook_chain_setup_transit, 0x66cd25a2u, "hook_chain_setup_transit"); \
    _MODVER_ENTRY(__modver_kh_fp_hook, 0x6d12a6f0u, "fp_hook"); \
    _MODVER_ENTRY(__modver_kh_fp_unhook, 0xc8ecc5d8u, "fp_unhook"); \
    _MODVER_ENTRY(__modver_kh_fp_hook_wrap, 0x8da53a4fu, "fp_hook_wrap"); \
    _MODVER_ENTRY(__modver_kh_fp_hook_unwrap, 0x019029a5u, "fp_hook_unwrap"); \
    _MODVER_ENTRY(__modver_kh_fp_hook_chain_setup_transit, 0xffd3212du, "fp_hook_chain_setup_transit"); \
    _MODVER_ENTRY(__modver_kh_ksyms_lookup, 0x866fa87bu, "ksyms_lookup")

#endif /* _KERNELHOOK_KH_SYMVERS_H_ */
